"#############################
"# General system-wide setup #
"#############################

function ResetAll()
  let @/ = ""
  echo "function ResetAll"
endfunction


" that changes often
"===================
color wombat256
"set background=light


"set visualbell

" default choice feature
"=======================

" Search
"-------
set ignorecase
"Override ignorecase if the search pattern contains upper case.
set smartcase
set incsearch
set hlsearch

" Indentation
"------------
"set smartindent
set autoindent
set expandtab 
set shiftwidth=2
set softtabstop=2
set tabstop=2
"set smarttab " is it useful ?

" that Not ! changes often
"-------------------------
set backspace=2
set encoding=utf8


" essential features
"===================
set nocompatible
let mapleader = ","
let maplocalleader = ","
syntax on
set nu
set mouse=a
set dir=~/tmp

" Spell checking
"---------------
" Pressing ,ss will toggle and untoggle spell checking
map ;ss :setlocal spell!<cr>
map ;s  :set spelllang=fr spell<cr>
"spell search forward
map zn  ]s
"spell search backward
map ZN  [s
" spellchecking
set spellfile=~/.vim/spell/fr.utf-8.add
set spellsuggest=10

"##############################
"# Key mappings for my macros #
"##############################
map <M-F12> :call ResetAll()<CR>

" close help
set  <S-F1>=^[[1;2P

if has("gui_running")
  map <S-F1> <Esc>:helpclose<CR>
else
  map [23~ <Esc>:helpclose<CR>
endif

" Edit vimrc
map ;ev :e! ~/.vimrc<cr>
map ;sv :source ~/.vimrc<cr>

" cd like cmd 
map ;cd :cd %:p:h<CR>:pwd<CR>

" Bind jj for esc
imap jj <Esc>:echo "-- NORMAL MODE --"<CR>

au filetype python      set omnifunc=pythoncomplete#Complete shiftwidth=4 tabstop=4 softtabstop=4
au filetype c           set omnifunc=ccomplete#Complete shiftwidth=8 tabstop=8 softtabstop=8 noexpandtab
au filetype glo        	set omnifunc=xmlcomplete#CompleteTags

"#############################
"# Script-specific settings  #
"#############################

" Patogen -  Load bundled plugins
"--------------------------------
call pathogen#runtime_append_all_bundles()
call pathogen#infect()
call pathogen#helptags()


" Ctag
"=====
map <F7> <Esc>:TlistToggle<CR>

" Plugin Project
"===============
map <F8> <Esc>:Project<CR>

" NerdTree
"=========
map <F9> <Esc>:NERDTreeToggle<CR>
let NERDTreeShowBookmarks=1

"#############################
"# Playground                #
"#############################
nmap <F9> <C-]>
map! <F9> <C-]>

"#############################
"# Includes                  #
"#############################

source $HOME/.vim/test.vim

